//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ButtonManager
{
	private ModeManager modeMgr
	{
		get;
		set;
	}

	private TimeManager timeMgr
	{
		get;
		set;
	}


	public ButtonManager()
	{
	}

	public virtual void DoIncrementHour()
	{
        if (modeMgr.GetMode() == Mode.SET_TIME)
        {
            timeMgr.IncrementCurrentHour();
        }
        else if (modeMgr.GetMode() == Mode.SET_ALARM)
        {
            timeMgr.IncrementAlarmHour();
        }
		
	}

	public virtual void DoIncrementMinute()
	{
        if (modeMgr.GetMode() == Mode.SET_TIME)
        {
            timeMgr.IncrementCurrentMinute();
        }
        else if (modeMgr.GetMode() == Mode.SET_ALARM)
        {
            timeMgr.IncrementAlarmMinute();
        }
    }

	public virtual void DoSnooze()
	{
		timeMgr.Snooze();
	}

	public virtual void DoSetTime()
	{
		modeMgr.SetMode(Mode.SET_TIME);
	}

	public virtual void DoSetAlarm()
	{
		modeMgr.SetMode(Mode.SET_ALARM);
	}

	public virtual void DoAlarmOn()
	{
		modeMgr.SetMode(Mode.ALARM_ON);
	}

	public virtual void DoAlarmOff()
	{
        modeMgr.SetMode(Mode.ALARM_OFF); ;
	}

	public virtual void SetModeManager(ModeManager newModeMgr)
	{
		modeMgr = newModeMgr;
	}

	public virtual void SetTimeManager(TimeManager newTimeMgr)
	{
        timeMgr = newTimeMgr;
	}

}

