//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Digital_ClockLib.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Clock
{
	private TimeManager TimeMgr
	{
		get;
		set;
	}

	private SixtySecondTimer timer
	{
		get;
		set;
	}

	private ModeManager ModeMgr
	{
		get;
		set;
	}

	private Display Display
	{
		get;
		set;
	}

	private Alarm Alarm
	{
		get;
		set;
	}

	private ButtonManager Button
	{
		get;
		set;
	}

	public virtual ButtonManager button
	{
		get;
		set;
	}

	public virtual ModeManager modeMgr
	{
		get;
		set;
	}

	public virtual TimeManager timeMgr
	{
		get;
		set;
	}

	public virtual Display display
	{
		get;
		set;
	}

	public virtual Alarm alarm
	{
		get;
		set;
	}

	public Clock()
	{
	}

	public virtual void Start()
	{
		throw new System.NotImplementedException();
	}

}

