//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Digital_ClockLib.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TimeManager
{
	private Time currentTime { get; set; }
	private Time alarmTime { get; set; }
    private Time snoozeTime { get; set; }
    private Display display { get; set; }
    private Alarm alarm { get; set; }
    private ModeManager modeMgr { get; set; }

	public TimeManager()
	{
	}

	public virtual void SetDisplay(Display newDisplay) { display = newDisplay; }
	public virtual void SetModeManager(ModeManager newModeManager) { modeMgr = newModeManager; }
	public virtual void SetAlarm(Alarm newAlarm) { alarm = newAlarm; }
	public virtual void IncrementCurrentMinute()
    {
        currentTime.IncrementMinute();
        if (currentTime.Equate(alarmTime))
        {
            alarm.On();
        }
    }
	public virtual void IncrementCurrentHour() { currentTime.IncrementHour(); }
	public virtual void IncrementAlarmHour() { alarmTime.IncrementHour(); }
	public virtual void IncrementAlarmMinute() { alarmTime.IncrementMinute(); }

	public virtual void Snooze()
	{
        alarm.Off();
        for (int i = 0; i != 10; i++)
        {
            alarmTime.IncrementMinute();
        }
	}

	public virtual void ShowCurrentTime()
	{
		display.ShowHour(currentTime.GetHour());
        display.ShowMinute(currentTime.GetMinute());
	}

	public virtual void ShowAlarmTime()
	{
        display.ShowHour(alarmTime.GetHour());
        display.ShowMinute(alarmTime.GetMinute());
    }

}

